---
functional:
  - Пользователь должен иметь возможность регистрации
  - Пользователь должен иметь возможность авторизации
  - Пользователь должен иметь возможность создания игр 
  - Пользователь должен иметь возможность играть без авторизации
  - Пользователь должен иметь возможность общаться в чате
  - Пользователь должен иметь возможность создания приглашения в игру
  - Пользователь должен иметь возможность выбрать игру по уровню сложности, продолжительности
  - Пользователь должен иметь возможность выбрать определенную игру 
  - Пользователь должен иметь возможность просматривать рейтинг за выбранный срок (месяц, неделя)
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров (Google Chrome, Safari, Firefox Browser, Opera)
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность выбрать язык сайта (английский, русский, испанский)
  - На сайте должна быть анимированные элементы  